steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', './Dockerfile', '-t', 'gcr.io/seguimiento-parlamentario-cl/session-processing', "."]

images:
  - 'gcr.io/seguimiento-parlamentario-cl/session-processing'